version: '3.7'
services:
  ws:
    build: ./ws
    volumes:
      - ./config:/root/config
      - ./bin:/root/bin
      - ./app:/root/app
      - go_modules:/root/gopath/pkg/mod
      - ./wd:/root/wd
      - ./scripts:/root/scripts
      - /tmp/.X11-unix:/tmp/.X11-unix
      - jetbrains_config:/root/.config/JetBrains
      - java_config:/root/.java
      - local:/root/.local
      - pip_packages:/usr/local/lib/python3.8/site-packages
      - java_hsperfdata:/tmp/hsperfdata_root
      - watson:/root/.config/watson
      - projects:/root/projects
    ports:
      - 18285:8285
      - 18286:8286
      - 18385:8385
      - 18386:8386
      - 14200:4200
      - 18000:8000
    stdin_open: true
    tty: true
    container_name: ws
    environment:
      DISPLAY:
    extra_hosts:
      - go.tvbit.local:0.0.0.0
    networks:
      default:
        aliases:
          - go.tvbit.local
  mysql:
    build: mysql
    volumes:
      - ./app:/mysql/app
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    container_name: mysql
  php:
    build: php
    volumes:
      - ./app:/root/app
    container_name: php
  web:
    build: ./web
    ports:
      - 10080:80
      - 10443:443
    networks:
      default:
        aliases:
          - public.tvbit.local
          - master.tvbit.local
    volumes:
      - ./app:/root/app
      - ./wd:/root/wd
    container_name: web
  clickhouse:
    build: ./clickhouse
    container_name: clickhouse
    ports:
      - 18123:8123
      - 19000:9000
    volumes:
      - clickhouse:/var/lib/clickhouse
volumes:
  mysql:
  go_modules:
  clickhouse:
  jetbrains_config:
  java_config:
  java_hsperfdata:
  local:
  pip_packages:
  watson:
  projects: