version: '3.7'
services:
  ws:
    build: ./ws
    volumes:
      - ./config:/root/config
      - ./app:/root/app
      - go_modules:/root/gopath/pkg/mod
      - ./go-wd:/root/go-wd
    ports:
      - 18285:8285
      - 18286:8286
      - 18385:8385
      - 18386:8386
      - 14200:4200
    stdin_open: true
    tty: true
    container_name: ws
    extra_hosts:
      - go.tvbit.local:0.0.0.0
    networks:
      default:
        aliases:
          - go.tvbit.local
  mysql:
    build: mysql
    volumes:
      - ./app:/mysql/app
      - mysql:/var/lib/mysql
    ports:
      - 13306:3306
    container_name: mysql
  php:
    build: php
    volumes:
      - ./app:/root/app
    container_name: php
  web:
    build: ./web
    ports:
      - 10080:80
      - 10443:443
    networks:
      default:
        aliases:
          - public.tvbit.local
          - master.tvbit.local
    volumes:
      - ./app:/root/app
      - ./go-wd:/root/go-wd
    container_name: web
  clickhouse:
    build: ./clickhouse
    container_name: clickhouse
    ports:
      - 18123:8123
      - 19000:9000
    volumes:
      - clickhouse:/var/lib/clickhouse
volumes:
  mysql:
  go_modules:
  clickhouse: